// Mission Control: Execute an approved action.
// Materializes the action into the appropriate destination (tasks, notifications)
// and logs the execution.
import { serve } from "https://deno.land/std@0.168.0/http/server.ts";
import { createClient } from "https://esm.sh/@supabase/supabase-js@2";

const corsHeaders = {
  "Access-Control-Allow-Origin": "*",
  "Access-Control-Allow-Headers": "authorization, x-client-info, apikey, content-type",
  "Access-Control-Allow-Methods": "POST, GET, OPTIONS",
};

const supabase = createClient(
  Deno.env.get("SUPABASE_URL")!,
  Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,
);

serve(async (req) => {
  if (req.method === "OPTIONS") return new Response("ok", { headers: corsHeaders });
  try {
    const body = await req.json().catch(() => ({}));
    const actionId: string | undefined = body.action_id;
    const editedContent: string | undefined = body.edited_content;
    if (!actionId) {
      return new Response(JSON.stringify({ error: "action_id required" }), {
        status: 400, headers: { ...corsHeaders, "Content-Type": "application/json" },
      });
    }

    const { data: action, error: aErr } = await supabase
      .from("mission_control_actions")
      .select("*")
      .eq("id", actionId)
      .single();
    if (aErr || !action) throw new Error(aErr?.message ?? "action not found");

    const content = editedContent ?? (action as any).draft_content;
    const actionType = (action as any).action_type as string;
    const title = (action as any).title as string;

    const dueDays = actionType === "grant_reminder" ? 3 : actionType === "donor_email" ? 5 : 7;
    const due = new Date(Date.now() + dueDays * 24 * 60 * 60 * 1000).toISOString().slice(0, 10);
    const priority = actionType === "grant_reminder" ? "high" : actionType === "donor_email" ? "high" : "medium";

    // Materialize into tasks table (every action becomes an actionable task)
    const { data: task, error: tErr } = await supabase
      .from("tasks")
      .insert({
        title: title.slice(0, 200),
        description: `${content}\n\n---\nGenerated by Mission Control · action_id: ${actionId}`,
        status: "pending",
        priority,
        due_date: due,
        created_by: (action as any).user_id ?? null,
      })
      .select()
      .single();
    if (tErr) throw new Error(`task insert failed: ${tErr.message}`);

    // Also create a notification so it surfaces in the activity feed
    const destination: Record<string, unknown> = { task_id: (task as any)?.id };
    try {
      await supabase.from("notifications").insert({
        title: `Mission Control: ${title.slice(0, 80)}`,
        message: content.slice(0, 400),
        type: "mission_control",
        user_id: (action as any).user_id ?? null,
      });
      destination.notification_created = true;
    } catch {
      // notifications schema may differ; non-fatal
    }

    const now = new Date().toISOString();
    const { error: uErr } = await supabase
      .from("mission_control_actions")
      .update({
        status: "executed",
        edited_content: editedContent ?? null,
        destination,
        approved_at: now,
        executed_at: now,
        updated_at: now,
      })
      .eq("id", actionId);
    if (uErr) throw new Error(`action update failed: ${uErr.message}`);

    return new Response(JSON.stringify({ ok: true, destination, task_id: (task as any)?.id }), {
      headers: { ...corsHeaders, "Content-Type": "application/json" },
    });
  } catch (e) {
    return new Response(
      JSON.stringify({ error: String((e as any)?.message ?? e) }),
      { status: 500, headers: { ...corsHeaders, "Content-Type": "application/json" } },
    );
  }
});
